name: Generate video from request

on: 
  workflow_dispatch:
    inputs:

      image:
        description: Image URL
      

jobs:
  ai:        
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        
    - name: Download image
      working-directory: scripts
      run: |
        

    - name: Config & run generator
      working-directory: scripts
      run: |
        export CONFIGPATH=config
        export RUNID=${{ github.run_id }}
        export RUNNUM=${{ github.run_number }}
        
        sh image.sh   

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: TMP-vid
        path: scripts/out

  cleanup:
    runs-on: ubuntu-latest
    needs: ai

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: scripts/tmp
        merge-multiple: true

    - name: Upload as 1 artifact
      uses: actions/upload-artifact@v4
      with:
        name: videos
        path: scripts/tmp

    - name: Cleanup artifacts
      uses: geekyeggo/delete-artifact@v4  
      with:
        name: TMP-*