name: Generate from request

on: 
  workflow_dispatch:
    inputs:

      prompt:
        description: Prompt

      enhance_prompt:
        type: boolean
        description: Enhance prompt by AI language model?

      width:
        type: number
        description: Width (dividable by 8)

      height:
        type: number
        description: Height (dividable by 8)

      upscale:
        type: choice
        description: Enhance and upscale width and height
        options: ['OFF', '2', '3', '4']
      
      multiplier:
        type: number
        description: Images per AI (AIs*x, 20 at once max), only when enhance is on
      

jobs:
  prompt:
    runs-on: ubuntu-latest
    outputs:
      step-output: ${{ steps.set-matrix.outputs.amount }}

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      if: ${{ github.event.inputs.enhance_prompt || !github.event.inputs.prompt }}
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Run prompt generator scripts
      id: set-matrix
      working-directory: scripts
      run: |
        export CONFIGPATH=config

        if [ -n "${{ github.event.inputs.prompt }}" ] && [ "${{ github.event.inputs.enhance_prompt }}" == false ]; then

          echo "Using prompt from input"
          echo "${{ github.event.inputs.prompt }}" > prompt.txt

          python amountHelper.py 1

        else

          if [ -n "${{ github.event.inputs.prompt }}" ]; then

            echo "Using prompt from input, enhancing..."
            export PROMPT="${{ github.event.inputs.prompt }}"

          fi

          if [ -n "${{ github.event.inputs.multiplier }}" ] && [ ${{ github.event.inputs.multiplier }} -gt 1 ]; then
            python amountHelper.py ${{ github.event.inputs.multiplier }}

            for ((i=0; i<${{ github.event.inputs.multiplier }}; i++)); do
              sh prompt.sh
              mv prompt.txt prompt-$i.txt
            done

          else
            python amountHelper.py 1
            sh prompt.sh
          fi
             
        fi

    - name: Upload prompt
      uses: actions/upload-artifact@v4
      with:
        name: prompt
        path: scripts/*.txt


  ai:
    strategy:
      matrix:
        model: [
          sd_xl_turbo_1.0.safetensors, 
          v2-1_768-ema-pruned.safetensors,
          v1-5-pruned-emaonly.safetensors,
        ]
        num: ${{fromJson(needs.prompt.outputs.step-output)}}
        
    runs-on: ubuntu-latest
    needs: prompt

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        
    - name: Download prompt
      uses: actions/download-artifact@v4
      with:
        name: prompt
        path: scripts

    - name: Config & run generator
      working-directory: scripts
      run: |
        export CONFIGPATH=config
        export MATRIXMODEL=${{ matrix.model }}
        export JOBINDEX=${{ strategy.job-index }}
        export RUNID=${{ github.run_id }}
        export RUNNUM=${{ github.run_number }}
        if [ -n "${{ github.event.inputs.width }}" ]; then
          echo "Using width from input ${{ github.event.inputs.width }}"
          export WIDTH="${{ github.event.inputs.width }}"
        else 
          export WIDTH="768"
        fi
        if [ -n "${{ github.event.inputs.height }}" ]; then
        echo "Using height from input ${{ github.event.inputs.height }}"
          export HEIGHT="${{ github.event.inputs.height }}"
        else 
          export HEIGHT="768"
        fi
        if [ -n "${{ github.event.inputs.upscale }}" ]; then
        echo "Using upscale from input ${{ github.event.inputs.upscale }}"
          export UPSCALE="${{ github.event.inputs.upscale }}"
        else 
          export UPSCALE="3"
        fi

        if [ "${{ github.event.inputs.enhance_prompt }}" == true ] && [ -n "${{ github.event.inputs.multiplier }}" ] && [ ${{ github.event.inputs.multiplier }} -gt 1 ]; then
          mv prompt-${{ matrix.num }}.txt prompt.txt
        fi
        
        sh image.sh   

    - name: Upload image
      uses: actions/upload-artifact@v4
      with:
        name: TMP-${{ matrix.model }}-${{ matrix.num }}
        path: scripts/out

  cleanup:
    runs-on: ubuntu-latest
    needs: ai

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Setup python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: scripts/tmp
        merge-multiple: true

    - name: Upload as 1 artifact
      uses: actions/upload-artifact@v4
      with:
        name: images
        path: scripts/tmp

    - name: Cleanup artifacts
      uses: geekyeggo/delete-artifact@v4  
      with:
        name: TMP-*